# Generated by Django 4.0.3 on 2022-04-20 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gadget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Устройство')),
                ('photo', models.URLField(verbose_name='Фото')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('category', models.CharField(choices=[('phones', 'Смартфоны'), ('desktops', 'Компьтеры'), ('laptops', 'Ноутбуки')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Отзыв')),
                ('rating', models.IntegerField(choices=[(1, 'Awful'), (2, 'Bad'), (3, 'Common'), (4, 'Good'), (5, 'Excellent')])),
                ('author_name', models.CharField(max_length=20, verbose_name='Автор')),
                ('date_published', models.DateField(verbose_name='Дата публикации')),
                ('to_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.gadget', verbose_name='Товар')),
            ],
        ),
    ]
